/** メッセージを管理する定数ファイル */
export const MESSAGE = {
  AUTH: {
    LOGIN_FAILED: 'ユーザーネームまたはパスワードが間違っています',
    REGIST_SUCCESS: 'アカウントの登録に成功しました',
    REGIST_FAILED: 'アカウントの作成に失敗しました',
    REGIST_DUPLICATE: 'このユーザー名は既に使用されています',
    UNAUTHORIZED: '認証が必要です',
    AUTH_INFO_FAILED: '認証情報の取得に失敗しました',
    ME_FETCH_FAILED: 'ユーザー情報の取得に失敗しました',
    NOT_FOUND: '指定されたユーザーが見つかりません',
    UPDATE_ME_SUCCESS: 'プロフィールを更新しました',
    UPDATE_ME_FAILED: 'プロフィールの更新に失敗しました',
  },
  DB: {
    DB_ERROR: 'データベースエラーが発生しました',
  },
  VALIDATION: {
    INVALID_INPUT: '入力値が不正です',
  },
  WEBAUTHN: {
    REGISTRATION_START_SUCCESS: '顔認証の登録を開始しました',
    REGISTRATION_SUCCESS: '顔認証の登録が完了しました',
    REGISTRATION_FAILED: '顔認証の登録に失敗しました',
    AUTHENTICATION_START_SUCCESS: '顔認証の認証を開始しました',
    AUTHENTICATION_SUCCESS: '顔認証による認証が完了しました',
    AUTHENTICATION_FAILED: '顔認証による認証に失敗しました',
    CHALLENGE_NOT_FOUND:
      '認証チャレンジが見つかりません。もう一度お試しください',
    CHALLENGE_EXPIRED:
      '認証チャレンジの有効期限が切れました。もう一度お試しください',
    NO_CREDENTIALS: '顔認証が登録されていません。先に顔認証を登録してください',
    CREDENTIAL_ALREADY_EXISTS: 'この認証器はすでに登録されています',
  },
  TASK: {
    CREATE_SUCCESS: 'タスクを作成しました',
    QUEUE_UPDATE_SUCCESS: 'タスクをキューで処理し更新しました',
    DELETE_SUCCESS: 'タスクを削除しました',
    NOT_FOUND: '指定されたタスクが見つかりません',
    CREATE_FAILED: 'タスクの作成に失敗しました',
    UPDATE_FAILED: 'タスクの更新に失敗しました',
    DELETE_FAILED: 'タスクの削除に失敗しました',
    CATEGORIES_FETCH_FAILED: 'カテゴリ一覧の取得に失敗しました',
    FORBIDDEN: 'このタスクを操作する権限がありません',
  },
  EVENT: {
    CREATE_SUCCESS: '予定を作成しました',
    UPDATE_SUCCESS: '予定を更新しました',
    DELETE_SUCCESS: '予定を削除しました',
    NOT_FOUND: '指定された予定が見つかりません',
    CREATE_FAILED: '予定の作成に失敗しました',
    UPDATE_FAILED: '予定の更新に失敗しました',
    DELETE_FAILED: '予定の削除に失敗しました',
    FORBIDDEN: 'この予定を操作する権限がありません',
    CREATE_MULTIPLE_FAILED: '複数予定の作成に失敗しました',
    REPEAT_LIMIT_EXCEEDED:
      '繰り返し予定の生成件数が上限（100件）を超えています',
    START_TIMES_REQUIRED: '開始日時を1つ以上指定してください',
    START_END_TIMES_LENGTH_MISMATCH:
      '開始日時と終了日時の件数が一致していません',
    UPDATE_GROUP_SUCCESS: '繰り返し予定を全て更新しました',
    UPDATE_GROUP_FAILED: '繰り返し予定の更新に失敗しました',
    REPEAT_GROUP_NOT_FOUND: '指定された繰り返しグループの予定が見つかりません',
    REPEAT_GROUP_FORBIDDEN: 'この繰り返し予定を操作する権限がありません',
    PERMISSION_FETCH_FAILED: '予定の権限一覧の取得に失敗しました',
    PERMISSION_ADD_SUCCESS: '予定の権限を付与しました',
    PERMISSION_ADD_FAILED: '予定の権限の付与に失敗しました',
    PERMISSION_REMOVE_SUCCESS: '予定の権限を削除しました',
    PERMISSION_REMOVE_FAILED: '予定の権限の削除に失敗しました',
    PROXY_GRANT_ADD_SUCCESS: '代理登録権限を付与しました',
    PROXY_GRANT_ADD_FAILED: '代理登録権限の付与に失敗しました',
    PROXY_GRANT_REMOVE_SUCCESS: '代理登録権限を削除しました',
    PROXY_GRANT_REMOVE_FAILED: '代理登録権限の削除に失敗しました',
    PROXY_GRANT_FETCH_FAILED: '代理登録権限一覧の取得に失敗しました',
    PROXY_GRANT_SELF_FORBIDDEN:
      '自分自身に代理登録権限を付与することはできません',
    PROXY_GRANT_NOT_FOUND: '指定された代理登録権限が見つかりません',
    PROXY_GRANT_FORBIDDEN: 'この予定に代理登録する権限がありません',
  },
  LINK: {
    CREATE_SUCCESS: 'リンクを作成しました',
    UPDATE_SUCCESS: 'リンクを更新しました',
    DELETE_SUCCESS: 'リンクを削除しました',
    NOT_FOUND: '指定されたリンクが見つかりません',
    CREATE_FAILED: 'リンクの作成に失敗しました',
    UPDATE_FAILED: 'リンクの更新に失敗しました',
    DELETE_FAILED: 'リンクの削除に失敗しました',
    FORBIDDEN: 'このリンクを操作する権限がありません',
    PARENT_NOT_FOLDER: '親要素にはフォルダのみ指定できます',
    URL_REQUIRED: 'リンクタイプにはURLが必須です',
    PARENT_NOT_FOUND: '指定された親フォルダが見つかりません',
  },
  PERMISSION: {
    ADD_SUCCESS: '権限を付与しました',
    REMOVE_SUCCESS: '権限を削除しました',
    NOT_FOUND: '指定された権限が見つかりません',
    ADD_FAILED: '権限の付与に失敗しました',
    REMOVE_FAILED: '権限の削除に失敗しました',
    FETCH_FAILED: '権限一覧の取得に失敗しました',
    FORBIDDEN: 'この操作を行う権限がありません',
    OWNER_ONLY: '権限の管理は作成者のみが行えます',
    ALREADY_EXISTS: '指定されたユーザーにはすでに権限が付与されています',
  },
  CHAT: {
    SEND_SUCCESS: 'メッセージを送信しました',
    SEND_FAILED: 'メッセージの送信に失敗しました',
    FETCH_FAILED: 'メッセージの取得に失敗しました',
    CONTACTS_FETCH_FAILED: 'チャット相手一覧の取得に失敗しました',
    USERS_FETCH_FAILED: 'ユーザー一覧の取得に失敗しました',
  },
};
