/** メッセージを管理する定数ファイル */
export const MESSAGE = {
  AUTH: {
    LOGIN_SUCCESS: 'ログイン成功',
    LOGIN_FAILED: 'ユーザーネームまたはパスワードが間違っています',
    REGIST_SUCCESS: 'アカウントの登録に成功しました',
    REGIST_FAILED: 'アカウントの作成に失敗しました',
    REGIST_DUPLICATE: 'このユーザー名は既に使用されています',
    UNAUTHORIZED: '認証が必要です',
    AUTH_INFO_FAILED: '認証情報の取得に失敗しました',
    LINE_LOGIN_URL_FAILED: 'LINE認証URLの生成に失敗しました',
    LINE_CALLBACK_FAILED: 'LINE連携に失敗しました',
    LINE_CALLBACK_SUCCESS: 'LINE連携が完了しました',
    ME_FETCH_FAILED: 'ユーザー情報の取得に失敗しました',
  },
  DB: {
    DB_ERROR: 'データベースエラーが発生しました',
  },
  VALIDATION: {
    INVALID_INPUT: '入力値が不正です',
  },
  TASK: {
    CREATE_SUCCESS: 'タスクを作成しました',
    UPDATE_SUCCESS: 'タスクを更新しました',
    QUEUE_UPDATE_SUCCESS: 'タスクをキューで処理し更新しました',
    DELETE_SUCCESS: 'タスクを削除しました',
    NOT_FOUND: '指定されたタスクが見つかりません',
    CREATE_FAILED: 'タスクの作成に失敗しました',
    UPDATE_FAILED: 'タスクの更新に失敗しました',
    DELETE_FAILED: 'タスクの削除に失敗しました',
    CATEGORIES_FETCH_FAILED: 'カテゴリ一覧の取得に失敗しました',
  },
  NOTIFICATION: {
    CREATE_SUCCESS: '通知を追加しました',
    DELETE_SUCCESS: '通知を削除しました',
    FETCH_SUCCESS: '通知一覧を取得しました',
    NOT_FOUND: '指定された通知が見つかりません',
    CREATE_FAILED: '通知の追加に失敗しました',
    DELETE_FAILED: '通知の削除に失敗しました',
    FETCH_FAILED: '通知一覧の取得に失敗しました',
    LINE_SEND_FAILED: 'LINE通知の送信に失敗しました',
  },
  EVENT: {
    CREATE_SUCCESS: '予定を作成しました',
    UPDATE_SUCCESS: '予定を更新しました',
    DELETE_SUCCESS: '予定を削除しました',
    NOT_FOUND: '指定された予定が見つかりません',
    CREATE_FAILED: '予定の作成に失敗しました',
    UPDATE_FAILED: '予定の更新に失敗しました',
    DELETE_FAILED: '予定の削除に失敗しました',
    FORBIDDEN: 'この予定を操作する権限がありません',
    CREATE_MULTIPLE_FAILED: '複数予定の作成に失敗しました',
    REPEAT_LIMIT_EXCEEDED:
      '繰り返し予定の生成件数が上限（100件）を超えています',
    START_TIMES_REQUIRED: '開始日時を1つ以上指定してください',
  },
  LINK: {
    CREATE_SUCCESS: 'リンクを作成しました',
    UPDATE_SUCCESS: 'リンクを更新しました',
    DELETE_SUCCESS: 'リンクを削除しました',
    NOT_FOUND: '指定されたリンクが見つかりません',
    CREATE_FAILED: 'リンクの作成に失敗しました',
    UPDATE_FAILED: 'リンクの更新に失敗しました',
    DELETE_FAILED: 'リンクの削除に失敗しました',
    FORBIDDEN: 'このリンクを削除する権限がありません',
    PARENT_NOT_FOLDER: '親要素にはフォルダのみ指定できます',
    URL_REQUIRED: 'リンクタイプにはURLが必須です',
    PARENT_NOT_FOUND: '指定された親フォルダが見つかりません',
  },
};
